// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kpfw.DataModels;

namespace kpfw.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190626155932_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kpfw.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AirDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Director")
                        .HasMaxLength(100);

                    b.Property<string>("ExecutiveProducer")
                        .HasMaxLength(200);

                    b.Property<string>("GuestStars")
                        .HasMaxLength(300);

                    b.Property<int>("Number");

                    b.Property<string>("Producer")
                        .HasMaxLength(100);

                    b.Property<string>("ProductionNumber")
                        .HasMaxLength(15);

                    b.Property<string>("Recap")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Stars")
                        .HasMaxLength(300);

                    b.Property<string>("Studio")
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Transcript")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("UrlLabel")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Writer")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Episode");
                });
#pragma warning restore 612, 618
        }
    }
}
